# version code ccaba3406664+
# Please fill out this stencil and submit using the provided submission script.


## 1: (Problem 12.14.1) Finding eigenvalues and -vectors
# Provide eigenvectors as lists.
# If there is only one eigenvalue for a part,
#   use None for one of them

# Part a
p1_part_a_eigenvalue1 = ...
p1_part_a_eigenvector1 = ...
p1_part_a_eigenvalue2 = ...
p1_part_a_eigenvector2 = ...

# Part b
p1_part_b_eigenvalue1 = ...
p1_part_b_eigenvector1 = ...
p1_part_b_eigenvalue2 = ...
p1_part_b_eigenvector2 = ...

# Part c
p1_part_c_eigenvalue1 = ...
p1_part_c_eigenvector1 = ...
p1_part_c_eigenvalue2 = ...
p1_part_c_eigenvector2 = ...

# Part d
p1_part_d_eigenvalue1 = ...
p1_part_d_eigenvector1 = ...
p1_part_d_eigenvalue2 = ...
p1_part_d_eigenvector2 = ...




## 2: (Problem 12.14.2) Finding eigenvectors
# Provide eigenvectors as lists.


# Part a
p2_part_a_lambda1_eigenvector = ...
p2_part_a_lambda2_eigenvector = ...

# Part b
p2_part_b_lambda1_eigenvector = ...
p2_part_b_lambda2_eigenvector = ...



## 3: (Problem 12.14.3) Finding the eigenvalue associated with an eigenvector
# Part a
p3_part_a_eigenvalue1 = ...
p3_part_a_eigenvalue2 = ...

# Part b
p3_part_b_eigenvalue1 = ...
p3_part_b_eigenvalue2 = ...



## 4: (Problem 12.14.11) Markov chains and eigenvectors
# a Mat
transition_matrix = ...

# a Vec
definitely_windy_vector = ...

day_after_windy = ...

uniform = ...
day_after_uniform = ...

four_hundred_days_from_now = ...

# Be clever here; no computation is needed:
eigenvalue = ...
eigenvector = ... # as an instance of Vec

